language: node_js

node_js: 8.9.3

sudo: false

cache:
  directories:
    # Location of npm cache per https://docs.npmjs.com/cli/cache#cache. Shared by npx per
    # https://github.com/zkat/npx/tree/6e89dbd5989366e52d3810692b1ab5889a05fbad#description.
    - $HOME/.npm

install:
  - npx npm@$NPM_VERSION ci

# Don’t build pushes to branches other than our published branches. This also affects PR
# builds since they test merge commits. If we didn’t have this config, every time we pushed
# to a branch involved in a PR, Travis would run both a PR build and a push build, consuming
# our concurrent builds. More info here https://mail.mixmax.com/m/YqyPRFXQrucgApTZl and here
# https://mail.mixmax.com/m/YmhZwv5k4v5GKOVV2.
branches:
  only:
    - master
